## Section 1

### Write a function that inputs a number and prints the multiplication table of that number

In [1]:
# multiplication table function
def func1():
    ## enter a number for its multiplication table
    n = int(input('Input a number:'))
    for i in range(1,13):
        print(f'{n} * {i} == {n*i}')
func1()

Input a number:12
12 * 1 == 12
12 * 2 == 24
12 * 3 == 36
12 * 4 == 48
12 * 5 == 60
12 * 6 == 72
12 * 7 == 84
12 * 8 == 96
12 * 9 == 108
12 * 10 == 120
12 * 11 == 132
12 * 12 == 144


### Write a program to print twin primes less than 1000. If two consecutive odd numbers are both prime then they are known as twin primes

In [2]:
# function to obtain odd_number
def odd_number():
    odd = []
    n = int(input('Input a number: '))
    for i in range(2, n+1):
        if i % 2 != 0:
            odd.append(i)
    return odd   

## function to determine if a number is a prime
def is_prime(a):
    for j in range(2,int(a/2)+1):
        if (a % j) == 0:
            return False
    else:
        return True

# function to obtain twinprime
def twinprime():
    twin_prime = []
    odd = odd_number()
    for i in range(len(odd)-1):
        if is_prime(odd[i]) and is_prime(odd[i+1]):
            twin_prime.append((odd[i], odd[i+1]))
    return twin_prime
twinprime()

Input a number: 1000


[(3, 5),
 (5, 7),
 (11, 13),
 (17, 19),
 (29, 31),
 (41, 43),
 (59, 61),
 (71, 73),
 (101, 103),
 (107, 109),
 (137, 139),
 (149, 151),
 (179, 181),
 (191, 193),
 (197, 199),
 (227, 229),
 (239, 241),
 (269, 271),
 (281, 283),
 (311, 313),
 (347, 349),
 (419, 421),
 (431, 433),
 (461, 463),
 (521, 523),
 (569, 571),
 (599, 601),
 (617, 619),
 (641, 643),
 (659, 661),
 (809, 811),
 (821, 823),
 (827, 829),
 (857, 859),
 (881, 883)]

#### Write a program to find out the prime factors of a number. Example: prime factors of 56 -2, 2, 2, 7

In [3]:
# function to obtain prime_factors of a number
def prime_factors():
    prime_factors = []
    number = int(input('Enter the number: '))
    value = number
    ''' A number can itself be prime or if not, all its prime factors will be less than or equal to its int(number/2)+1'''
    for i in range(2, int(number/2) +1):
        if is_prime(i) and number % i == 0:
            while (number% i) == 0:
                prime_factors.append(i)
                number/=i
    return f'{value} - {prime_factors}'
prime_factors()             

Enter the number: 56


'56 - [2, 2, 2, 7]'

### Write a program which can filter odd numbers in a list by using filter function

In [5]:
# function to filter odd numbers from a list
def is_odd(value):
    if value % 2 != 0:
        return value
def filter_odd():
    number = int(input('Enter the number: '))
    value = list(filter(is_odd, [i for i in range(number+1)]))
    return value
filter_odd()

Enter the number: 19


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

### Write a function prodDigits() that inputs a number and returns the product of digits of that number.

In [7]:
# function to return product of digits of a number
def prodDigits():
    number = str(input('Enter the number: '))
    prod = 1
    # if the number is a unit, return the number
    if len(number) == 1:
        return int(number)
    else:
        for i in range(len(number)):
            prod *= int(number[i])
    return prod
prodDigits()

Enter the number: 12345


120

## Section 2

### Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [8]:
# convert list to numpy
import numpy as np
Original_list = [12.23, 13.32, 100, 36.32]
print(np.array(Original_list))

[ 12.23  13.32 100.    36.32]


### Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [9]:
# reshape an array to required shape
print(np.reshape(np.array(range(2, 11)), (3,3)))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

In [10]:
# function to update a null vector, its index and value
def update(index= 6, value = 11 ):
    arr = np.zeros((10,))
    arr[index] = value
    return arr
update()

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])